-- Slide 16
SELECT 	F.CD_FUNC, 
		F.NM_FUNCIONARIO, 
		INITCAP(F.NM_FUNCIONARIO) NOME_FUNC_INITCAP,
		UPPER(F.NM_FUNCIONARIO) NOME_FUNC_UPPER,
        LOWER(F.NM_FUNCIONARIO) NOME_FUNC_LOWER,
		LENGTH(F.NM_FUNCIONARIO) QTDE_BYTES_NOME_FUNC,
		SUBSTR(F.NM_FUNCIONARIO,1, INSTR(F.NM_FUNCIONARIO, ' ')) PRIMEIRO_NOME_FUNC,
		SUBSTR(F.NM_FUNCIONARIO, INSTR(F.NM_FUNCIONARIO, ' ' , -1), LENGTH(F.NM_FUNCIONARIO)) SOBRENOME
FROM 	T_SIP_FUNCIONARIO F
ORDER BY F.NM_FUNCIONARIO;


-- Slide 17
SELECT 	F.CD_FUNC, 
		F.NM_FUNCIONARIO, 
		INITCAP(F.NM_FUNCIONARIO) NOME_FUNC_INITCAP,
		UPPER(F.NM_FUNCIONARIO) NOME_FUNC_UPPER,
        LOWER(F.NM_FUNCIONARIO) NOME_FUNC_LOWER
FROM 	T_SIP_FUNCIONARIO F
WHERE   LOWER(F.NM_FUNCIONARIO) LIKE 'MA%'
ORDER BY F.NM_FUNCIONARIO;

SELECT 	F.CD_FUNC, 
		F.NM_FUNCIONARIO, 
		INITCAP(F.NM_FUNCIONARIO) NOME_FUNC_INITCAP,
		UPPER(F.NM_FUNCIONARIO) NOME_FUNC_UPPER,
        LOWER(F.NM_FUNCIONARIO) NOME_FUNC_LOWER
FROM 	T_SIP_FUNCIONARIO F
WHERE   UPPER(F.NM_FUNCIONARIO) LIKE 'MA%'
ORDER BY F.NM_FUNCIONARIO;

--
--  Slide 20
SELECT 	D.CD_DEPTO,
		D.NM_DEPTO,
		F.CD_FUNC, 
		F.NM_FUNCIONARIO, 
		F.VL_SALARIO,
		ROUND(F.VL_SALARIO,1) Salario_round_1,
		ROUND(F.VL_SALARIO,0) Salario_round_0,
		TRUNC(F.VL_SALARIO,1) Salario_trunc_1		
FROM 	T_SIP_FUNCIONARIO F INNER JOIN T_SIP_DEPTO D
ON (F.CD_DEPTO = D.CD_DEPTO);

--MOD
SELECT MOD(3,2) FROM DUAL;

-- Slide 23
SELECT SYSDATE, USER FROM DUAL;

-- Slide 25
SELECT SYSDATE, SYSDATE+7 Data_depois_7dias, USER FROM DUAL;

-- Slide 26
SELECT SYSDATE - TO_DATE('18/05/1990','DD/MM/YYYY') Qtd_dias_de_vida FROM DUAL;

-- Slide 28
SELECT SYSDATE, ADD_MONTHS(SYSDATE, 6) Seis_Meses_Depois FROM DUAL;

-- Slide 38
SELECT 	F.CD_FUNC, 
		F.NM_FUNCIONARIO, 
		F.DS_ESTADO_CIVIL,
		F.DT_NASCIMENTO,
		T.CD_TELEFONE SEQUENCIA_TELEFONE,
        T.NR_TELEFONE,
        --CONCAT( CONCAT( '(', T.NR_DDD ), ') ') ,
		--CONCAT(T.NR_DDD, ' ', CONCAT(T.NR_TELEFONE,' ')) NUMERO_TELEFONE,
        '('||T.NR_DDD||') ' || SUBSTR(T.NR_TELEFONE,1,LENGTH(T.NR_TELEFONE)-4)||'-'||SUBSTR(T.NR_TELEFONE,-4,4) NUMERO_TELEFONE,
		DECODE(T.TP_TELEFONE, 1, 'RESIDENCIAL', 2, 'CELULAR PROPRIO', 3, 'COMERCIAL', 'OUTROS') TIPO_TELEFONE
FROM 	T_SIP_FUNCIONARIO F INNER JOIN T_SIP_TELEFONE T
ON 		(F.CD_FUNC = T.CD_FUNC);

-- FUNÇÕES DE GRUPO

-- Slide 46
SELECT 	MAX(F.VL_SALARIO) VL_MAIOR_SALARIO,
		MIN(F.VL_SALARIO) VL_MENOR_SALARIO,
		ROUND(AVG(F.VL_SALARIO),2) VL_MEDIO_SALARIO,
		SUM(F.VL_SALARIO) VL_TOTAL_SALARIO
FROM	T_SIP_FUNCIONARIO F;

-- Slide 47
SELECT 	MIN(F.DT_NASCIMENTO) DT_MAIS_ANTIGA,
		MAX(F.DT_NASCIMENTO) DT_MAIS_NOVA
FROM	T_SIP_FUNCIONARIO F;


-- Slide 48
SELECT COUNT(*) QTD_LINHAS, COUNT(P.DT_TERMINO)
FROM T_SIP_PROJETO P; 

-- Slide 51
SELECT 	D.CD_DEPTO,
		D.NM_DEPTO,
		MAX( F.VL_SALARIO ) MAIOR_SALARIO_DEPTO,
		MIN( F.VL_SALARIO ) MENOR_SALARIO_DEPTO,
		AVG( F.VL_SALARIO ) MEDIA_SALARIAL_DEPTO,
		SUM( F.VL_SALARIO ) SOMA_TOTAL_SALARIO_DEPTO,
		COUNT(*) 			QTDE_FUNC_DEPTO		
FROM 	T_SIP_FUNCIONARIO F INNER JOIN T_SIP_DEPTO D
ON (F.CD_DEPTO = D.CD_DEPTO)
WHERE D.CD_DEPTO  = 4
GROUP BY D.CD_DEPTO,
		D.NM_DEPTO;
        
-- Slide 55
SELECT 	D.CD_DEPTO,
		D.NM_DEPTO,
		MAX( F.VL_SALARIO ) MAIOR_SALARIO_DEPTO,
		MIN( F.VL_SALARIO ) MENOR_SALARIO_DEPTO,
		ROUND(AVG( F.VL_SALARIO ),2) MEDIA_SALARIAL_DEPTO,
		SUM( F.VL_SALARIO ) SOMA_TOTAL_SALARIO_DEPTO,
		COUNT(*) 			QTDE_FUNC_DEPTO		
FROM 	T_SIP_FUNCIONARIO F INNER JOIN T_SIP_DEPTO D
ON (F.CD_DEPTO = D.CD_DEPTO)
GROUP BY D.CD_DEPTO,
		D.NM_DEPTO
HAVING COUNT(*) > 5
ORDER BY COUNT(*) ASC;

