--01
SELECT * FROM T_SIP_FUNCIONARIO;

--02
SELECT CD_FUNC,
       NM_FUNCIONARIO,
       DT_NASCIMENTO,
       CD_DEPTO
FROM T_SIP_FUNCIONARIO;

--

SELECT T_SIP_FUNCIONARIO.CD_FUNC,
       T_SIP_FUNCIONARIO.NM_FUNCIONARIO,
       T_SIP_FUNCIONARIO.DT_NASCIMENTO,
       T_SIP_FUNCIONARIO.CD_DEPTO;

--03
SELECT FUNC.CD_FUNC,
       FUNC.NM_FUNCIONARIO,
       FUNC.VL_SALARIO,
       FUNC.CD_DEPTO
FROM T_SIP_FUNCIONARIO FUNC --FUNC SENDO "APELIDO" DA TABELA
WHERE FUNC.CD_DEPTO = 6;

--04
SELECT DISTINCT F.CD_DEPTO --DISTINCT TRAZ TODAS AS POSSIVEIS OPÇÕES
FROM T_SIP_FUNCIONARIO FUNC;

--



--05
SELECT FUNC.CD_FUNC,
       FUNC.NM_FUNCIONARIO,
       FUNC.VL_SALARIO,
       FUNC.VL_SALARIO * 1,05
FROM T_SIP_FUNCIONARIO FUNC;

--06
SELECT FUNC.CD_FUNC,
       FUNC.NM_FUNCIONARIO,
       FUNC.VL_SALARIO,
       (FUNC.VL_SALARIO * 12) + 1000 VL_SALARIO_ANUAL --IGUAL AO SALARIO ANUAL, CRIANDO UMA COLUNA NO SELECT
FROM T_SIP_FUNCIONARIO FUNC;
       
--07
SELECT FUNC.CD_FUNC,
       FUNC.NM_FUNCIONARIO,
       FUNC.VL_SALARIO,
       FUNC.VL_SALARIO * 1.05 "VALOR AJUSTADO" -- ASPAS DUPLAS OBRIGATÓRIA QUANDO SE TEM UM ESPAÇO NO APELIDO DA COLUNA
       
--08
SELECT DEP.CD_DEPTO,
       DEP.NM_DEPTO,
FROM T_SIP_DEPTO DEP
       
       
--09
SELECT DEP.CD_DEPTO,
       DEP.NM_DEPTO
FROM T_SIP_DEPTO DEP
ORDER BY DEP.CD_DEPTO DESC; --ORDERNADOS DO MAIOR CÓDIGO PARA O MENOR

--

SELECT FUN.NM_FUNCIONARIO, F.VL_SALARIO
FROM T_SIP_FUNCIONARIO FUNC
ORDER BY F.VL_SALARIO DESC; --ORDERNADOS DO MAIOR SALARIO PARA O MENOR

--10
SELECT FUNC.CD_DEPTO,
       FUNC.NM_FUNCIONARIO,
       FUNC.VL_SALARIO,
       FUNC.CD_DEPTO
FROM T_SIP_FUNCIONARIO FUNC
WHERE FUNC.CD_DEPTO > 1
ORDER BY 4, NM_FUNCIONARIO DESC; -- 4 SENDO "CD_DEPTO" INDICIDE DA COLUNA DO SELECT, 2 SENDO "NM_FUNCIOARIO" INDICIDE DA COLUNA DO SELECT

--11
SELECT F.CD_FUNC MATRICULA,
       F.NM_FUNCIONARIO NOME_FUNCIONARIO,
       F.VL_SALARIO "SALÁRIO BRUTO",
       F.CD_DEPTO CODIGO_DEPARTAMENTO
FROM T_SIP_FUNCIONARIO F

--12 OP: >,<, <=, >=, AND, OR, NOT, IN
SELECT F.CD_FUNC MATRICULA,
       F.NM_FUNCIONARIO NOME_FUNCIONARIO,
       F.VL_SALARIO "SALÁRIO BRUTO",
       F.CD_DEPTO CODIGO_DEPARTAMENTO
FROM T_SIP_FUNCIONARIO F
WHERE VL_SALARIO > 2999.99
ORDER BY F.VL_SALARIO DESC;

--13
SELECT F.CD_FUNC MATRICULA,
       F.NM_FUNCIONARIO NOME_FUNCIONARIO,
       F.VL_SALARIO "SALÁRIO BRUTO",
       F.CD_DEPTO CODIGO_DEPARTAMENTO
FROM T_SIP_FUNCIONARIO F
WHERE F.NM_FUNCIONARIO = 'MARINA SILVA'; --SEMPRE ASPAS SIMPLES, COM EXCESSÃO 

--14
DELETE FROM T_SIP_FUNCIONARIO F WHERE F._NM_FUNCIONARIO 'MARINA SILVA'; -- DARÁ ERRO, POIS ELA POSSIU UMA CONSTRAINT 

--15
SELECT * FROM T_SIP_FUNCIONARIO FUNCIO
WHERE FUNCIO.DT_ADMISSAO >= TO_DATE('01/01/2018','DD/MM/YYYY');

--16
SELECT F.CD_FUNC,
       F.NM_FUNCIONARIO,
       F.CD_DEPTO,
       F.DT_ADMISSAO
FROM T_SIP_FUNCIONARIO F
WHERE F.DT_ADMISSAO >= TO_DATE('01/01/2012','DD/MM/YYYY')
AND 'TRUE'='TRUE'; --COLOCANDO DOIS VALORES IGUAIS TEXTO OU NUMERO. (2=2)

--17
SELECT F.CD_FUNC,
       F.NM_FUNCIONARIO,
       F.CD_DEPTO,
       F.DT_ADMISSAO
FROM T_SIP_FUNCIONARIO F
WHERE F.DT_ADMISSAO >= TO_DATE('01/01/2018','DD/MM/YYYY')
OR F.CD_DEPTO = 7;

--18
SELECT F.CD_FUNC,
       F.NM_FUNCIONARIO,
       F.CD_DEPTO,
       F.DT_ADMISSAO,
       F.VL_SALARIO
FROM T_SIP_FUNCIONARIO F
WHERE NOT F.CD_DEPTO = 10;

--19
SELECT F.CD_FUNC,
       F.NM_FUNCIONARIO,
       F.CD_DEPTO,
       F.DT_ADMISSAO,
       F.VL_SALARIO
FROM T_SIP_FUNCIONARIO F
WHERE F.DT_ADMISSAO BETWEEN TO_DATE ('01/01/2021','DD/MM//YYYY')
AND TO_DATE('31/12/2021','DD/MM/YYYY');

--20
SELECT F.CD_FUNC,
       F.NM_FUNCIONARIO,
       F.CD_DEPTO,
       F.DT_ADMISSAO,
       F.VL_SALARIO
FROM T_SIP_FUNCIONARIO F
WHERE F.CD_DEPTO IN (1,7,4);

--21
SELECT F.CD_FUNC,
       F.NM_FUNCIONARIO,
       F.CD_DEPTO,
       F.DT_ADMISSAO,
       F.VL_SALARIO
FROM T_SIP_FUNCIONARIO F
WHERE TO_CHAR(F.DT_ADMISSAO,'YYYY') IN ('2015', '2018', '2021') -- CONVERTENDO UMA DATA EM UMA STRING

--

SELECT F.CD_FUNC,
       F.NM_FUNCIONARIO,
       F.CD_DEPTO,
       F.DT_ADMISSAO,
       F.VL_SALARIO
FROM T_SIP_FUNCIONARIO F
WHERE F.CD_DEPTO NOT IN (1,7,4);