CREATE TABLE ddd_carro(
placa VARCHAR2(7) PRIMARY KEY,
cor VARCHAR2(20),
descricao VARCHAR2(100)
);

CREATE TABLE DDD_CLIENTE(
ID_CLIENTE NUMBER PRIMARY KEY,
NOME_CLIENTE VARCHAR2(30),
PLACA VARCHAR2 (7) NOT NULL,
FOREIGN KEY(PLACA) REFERENCES DDD_CARRO(PLACA)
);