create table t_py_mesagem (
    id number generated by default as identity,
    assunto varchar2(100),
    destinatario varchar2(100),
    remetente varchar2(100),
    conteudo varchar2(150),
    primary key(id)
    )
