CREATE TABLE PY_FILMES (
    NOME_FILME VARCHAR2(100) NOT NULL,
    DIRETOR_FILME VARCHAR2(100) NOT NULL,
    DATA_LANCAMENTO DATE NOT NULL
);

ALTER TABLE PY_FILMES ADD CONSTRAINT PK_PY_FILMES PRIMARY KEY (NOME_FILME);

DROP TABLE PY_FILMES;