CREATE TABLE t_ckp_categoria (
    cd_categoria  NUMBER(3) NOT NULL,
    ds_sigla_categoria  CHAR(3) NOT NULL,
    ds_categoria  VARCHAR2(30) NOT NULL
);

ALTER TABLE t_ckp_categoria ADD CONSTRAINT pk_ckp_categoria PRIMARY KEY ( cd_categoria );
ALTER TABLE t_ckp_categoria ADD CONSTRAINT un_ckp_categoria_sigla UNIQUE (ds_sigla_categoria);
ALTER TABLE t_ckp_categoria ADD CONSTRAINT un_ckp_categoria_desc UNIQUE (ds_categoria);

CREATE TABLE t_ckp_livro (
    nr_isbn  NUMBER(8) NOT NULL,
    nm_titulo  VARCHAR2(50) NOT NULL,
    ds_sinopse VARCHAR2(200) NOT NULL,
    nr_edicao NUMBER(2) NOT NULL,
    nr_ano NUMBER(4) NOT NULL,
    cd_categoria NUMBER(3) NOT NULL
);

ALTER TABLE t_ckp_livro ADD CONSTRAINT pk_ckp_livro PRIMARY KEY ( nr_isbn );
ALTER TABLE t_ckp_livro ADD CONSTRAINT fk_ckp_livro_categoria FOREIGN KEY ( cd_categoria ) REFERENCES t_ckp_categoria(cd_categoria);
ALTER TABLE t_ckp_livro ADD CONSTRAINT ck_ckp_livro_edicao CHECK (nr_edicao > 0);
ALTER TABLE t_ckp_livro ADD CONSTRAINT ck_ckp_livro_livro_ano CHECK (nr_ano > 0);

CREATE TABLE t_ckp_autor_livro (
    nr_isbn  NUMBER(8) NOT NULL,
    cd_autor  NUMBER(3) NOT NULL,
    st_autor_principal  NUMBER(1) NOT NULL
);

ALTER TABLE t_ckp_autor_livro ADD CONSTRAINT pk_ckp_autor_livro PRIMARY KEY ( nr_isbn,cd_autor );
ALTER TABLE t_ckp_autor_livro ADD CONSTRAINT fk_ckp_autor_livro FOREIGN KEY ( nr_isbn ) REFERENCES t_ckp_livro(nr_isbn);
ALTER TABLE t_ckp_autor_livro ADD CONSTRAINT fk_ckp_autor_livro_autor FOREIGN KEY ( cd_autor ) REFERENCES t_ckp_autor(cd_autor);
ALTER TABLE t_ckp_autor_livro ADD CONSTRAINT ck_ckp_autor_livro_status CHECK (st_autor_principal in (1,2));

CREATE TABLE t_ckp_autor(
    cd_autor  NUMBER(3) NOT NULL,
    nm_primeiro_autor  VARCHAR2(20) NOT NULL,
    nm_segundo_autor VARCHAR2(40) NOT NULL
);

ALTER TABLE t_ckp_autor ADD CONSTRAINT pk_ckp_autor PRIMARY KEY ( cd_autor );

ALTER TABLE T_CKP_CATEGORIA RENAME COLUMN DS_SIGLA_CATEGORIA TO DS_SIGLA_CATEG;

DESC T_CKP_cATEGORIA

ALTER TABLE T_CKP_CATEGORIA RENAME CONSTRAINT UN_CKP_CATEGORIA_DESC TO UN_CKP_CATEG_DESC;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'T_CKP_CATEGORIA'    ;

ALTER TABLE T_CKP_AUTOR MODIFY NM_SEGUNDO_AUTOR VARCHAR2 (30);

DESC T_CKP_AUTOR

ALTER TABLE T_CKP_AUTOR ADD DS_EMAIL VARCHAR(40) NOT NULL;

DESC T_CKP_AUTOR

ALTER TABLE T_CKP_AUTOR MODIFY DS_EMAIL VARCHAR2(60) NULL;

DESC T_CKP_AUTOR

ALTER TABLE T_CKP_AUTOR_LIVRO MODIFY NR_ISBN NUMBER (13);

DESC T_CKP_AUTOR_LIVRO

ALTER TABLE T_CKP_LIVRO MODIFY NR_ISBN NUMBER (13);

DESC T_CKP_LIVRO

ALTER TABLE T_CKP_AUTOR ADD NM_PAIS_ORIGEM VARCHAR2 (30) NULL;

DESC T_CKP_AUTOR

ALTER TABLE T_CKP_LIVRO ADD CONSTRAINT UN_CKP_LIVRO_TITULO UNIQUE (nm_titulo);

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'T_CKP_LIVRO'    ;

ALTER TABLE T_CKP_AUTOR_LIVRO DROP CONSTRAINT FK_CKP_AUTOR_LIVRO_AUTOR;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'T_CKP_AUTOR_LIVRO'    ;

ALTER TABLE T_CKP_LIVRO DROP CONSTRAINT PK_CKP_LIVRO CASCADE;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'T_CKP_LIVRO'    ;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'T_CKP_AUTOR_LIVRO'    ;

ALTER TABLE T_CKP_CATEGORIA MODIFY CONSTRAINT UN_CKP_CATEGORIA_SIGLA DISABLE;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'T_CKP_CATEGORIA'    ;




