ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';

INSERT INTO  T_SIP_DEPTO (CD_DEPTO, NM_DEPTO, SG_DEPTO)
VALUES (1,'FINANCEIRO','FIN');

INSERT INTO  T_SIP_DEPTO (CD_DEPTO, NM_DEPTO, SG_DEPTO)
VALUES (2,'TI','TI');


COMMIT;

SELECT * FROM T_SIP_DEPTO;

ALTER TABLE T_SIP_PROJETO RENAME COLUMN DT_INCIIO TO DT_INICIO;

--INSERT INTO  T_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO)
--VALUES (1,'FIAP', TO_DATE('01/02/2023',20-08-00, '01/02/2023',20-00-00),

INSERT INTO  T_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO)
VALUES (1,'FIAP', TO_DATE('01/02/2023','DD/MM/YYYY'),
TO_DATE('01/02/2024','DD/MM/YYYY'));

INSERT INTO  T_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO)
VALUES (2,'FIAP_2', TO_DATE('01/02/2023','DD/MM/YYYY'),
TO_DATE('01/02/2024','DD/MM/YYYY'));

INSERT INTO  T_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO)
VALUES (3,'FIAP_3', TO_DATE('01/02/2023','DD/MM/YYYY'),
TO_DATE('01/02/2024','DD/MM/YYYY'));

INSERT INTO  T_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO)
VALUES (4,'FIAP_4', TO_DATE('01/02/2023','DD/MM/YYYY'), NULL);

COMMIT;

SELECT * FROM T_SIP_PROJETO;

CREATE TABLE T_COPY_SIP_PROJETO AS
SELECT * FROM T_SIP_PROJETO WHERE 1=2; --PARA PEGARMOS APENAS A ESTRUTURA USAMOS WHERE 1=2 OR TRUE=FALSE

INSERT INTO T_COPY_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO)
(SELECT CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO --OR SELECT * APENAS
    FROM T_SIP_PROJETO
    WHERE DT_TERMINO IS NOT NULL);
    

 DROP TABLE T_COPY_SIP_PROJETO;
 CREATE TABLE T_COPY_SIP_PROJETO AS
 SELECT *
    FROM T_SIP_PROJETO
    WHERE DT_TERMINO IS NOT NULL;
    
SELECT * FROM T_COPY_SIP_PROJETO;

--UPDATE COM SUBQUERY
SELECT * FROM T_SIP_PROJETO;
UPDATE T_SIP_PROJETO
SET DT_TERMINO = (SELECT DT_TERMINO FROM T_SIP_PROJETO WHERE CD_PROJETO = 1);

DESCRIBE T_SIP_FUNCIONARIO;

INSERT INTO T_SIP_FUNCIONARIO
VALUES (1,2,'ALANA',TO_DATE('25/01/2006','DD/MM/YYYY'),
TO_DATE('01/02/2023','DD/MM/YYYY'),1400.00);

UPDATE T_SIP_FUNCIONARIO
SET NM_FUNCIONARIO = 'JOSÉ',
    DT_NASCIMENTO = TO_DATE('01/02/1965','DD/MM/YYYY')
WHERE NR_MATRICULA = 1;

SELECT * FROM T_SIP_FUNCIONARIO;

UPDATE T_SIP_FUNCIONARIO
SET VL_SALARIO = VL_SALARIO * 1.055
WHERE NR_MATRICULA = 1;

COMMIT;

DELETE FROM T_SIP_FUNCIONARIO
WHERE NR_MATRICULA = 1;

DELETE FROM T_SIP_DEPTO;
ROLLBACK;

DROP TABLE T_SIP_DEPTO CASCADE CONSTRAINTS;

COMMIT;



