CREATE TABLE T_CKP_CATEGORIA(
    CD_CATEGORIA    NUMBER(3)   NOT NULL,
    DS_SIGLA_CATEGORIA  CHAR(3) NOT NULL,
    DS_CATEGORIA    VARCHAR2(30)    NOT NULL
);

ALTER TABLE T_CKP_CATEGORIA ADD CONSTRAINT PK_CKP_CATEGORIA PRIMARY KEY (CD_CATEGORIA);
ALTER TABLE T_CKP_CATEGORIA ADD CONSTRAINT PK_CKP_CATEGORIA_SIGLA UNIQUE (DS_SIGLA_CATEGORIA);
ALTER TABLE T_CKP_CATEGORIA ADD CONSTRAINT PK_CKP_CATEGORIA_DESC UNIQUE (DS_CATEGORIA);

CREATE TABLE T_CKP_LIVROS (
    NR_ISBN     NUMBER(8)   NOT NULL CONSTRAINT PK_CKP_LIVRO PRIMARY KEY,
    CD_CATEGORIA    NUMBER(3)   NOT NULL,
    NM_TITULO       VARCHAR2(50)    NOT NULL,
    DS_SINOPSE      VARCHAR2(200)   NOT NULL,
    NR_EDICAO   NUMBER(2)   NOT NULL,
    NR_ANO  NUMBER(4)   NOT NULL
);

ALTER TABLE T_CKP_LIVROS ADD CONSTRAINT FK_CKP_LIVRO_CATEGORIA FOREIGN KEY (CD_CATEGORIA)
REFERENCES T_CKP_CATEGORIA(CD_CATEGORIA);

CREATE TABLE T_CKP_AUTOR_LIVRO(
    NR_ISBN     NUMBER(8)   NOT NULL,
    CD_AUTOR    NUMBER(3)   NOT NULL,
    ST_AUTOR_PRINCIPAL NUMBER(1) NOT NULL,
    CONSTRAINT PK_CKP_AUTOR_LIVRO PRIMARY KEY (NR_ISBN,CD_AUTOR)
);

ALTER TABLE T_CKP_LIVROS ADD CONSTRAINT FK_CKP_AUTOR_LIVRO FOREIGN KEY (CD_CATEGORIA)
REFERENCES T_CKP_LIVROS(NR_ISBN);

CREATE TABLE T_CKP_AUTOR(
    CD_AUTOR    NUMBER(3)NOT NULL CONSTRAINT PK_CKP_AUTOR PRIMARY KEY,
    NM_PRIMEIRO_AUTOR   VARCHAR2(20) NOT NULL,
    NM_SEGUNDO_AUTOR   VARCHAR2(20) NOT NULL
);

ALTER TABLE T_CKP_AUTOR_LIVRO ADD CONSTRAINT FK_CKP_LIVRO_AUTOR FOREIGN KEY (CD_AUTOR)
REFERENCES T_CKP_AUTOR(CD_AUTOR);