-- Slide 10
SELECT 	T_SIP_FUNCIONARIO.CD_FUNC, 
		T_SIP_FUNCIONARIO.NM_FUNCIONARIO, 
		T_SIP_FUNCIONARIO.DT_ADMISSAO, 
		T_SIP_FUNCIONARIO.VL_SALARIO
FROM 	T_SIP_FUNCIONARIO;

-- Slide 11
SELECT 	F.CD_FUNC, 
		F.NM_FUNCIONARIO, 
		F.DT_ADMISSAO, 
		F.VL_SALARIO
FROM 	T_SIP_FUNCIONARIO F;

-- Slide 18
-- SQL99
SELECT 	D.CD_DEPTO,
		D.NM_DEPTO,
		F.CD_FUNC, 
		F.NM_FUNCIONARIO, 
		F.DT_ADMISSAO, 
		F.VL_SALARIO
FROM 	T_SIP_FUNCIONARIO F INNER JOIN T_SIP_DEPTO D
ON (F.CD_DEPTO = D.CD_DEPTO);

-- ANTERIOR AO SQL99
SELECT 	D.CD_DEPTO,
		D.NM_DEPTO,
		F.CD_FUNC, 
		F.NM_FUNCIONARIO, 
		F.DT_ADMISSAO, 
		F.VL_SALARIO
FROM 	T_SIP_FUNCIONARIO F, T_SIP_DEPTO D
WHERE   F.CD_DEPTO = D.CD_DEPTO;

-- Slide 24
SELECT 	F.CD_FUNC, 
		F.NM_FUNCIONARIO, 
		F.DS_ESTADO_CIVIL,
		F.DT_NASCIMENTO,
		D.ID_DEPENDENTE NUMERO_DEPENDENTE,
		D.NM_DEPENDENTE,
		D.DT_NASCIMENTO
FROM 	T_SIP_FUNCIONARIO F INNER JOIN T_SIP_DEPENDENTE D
ON 		(F.CD_FUNC = D.CD_FUNC);

-- Slide 26
SELECT 	F.CD_FUNC CODIGO_FUNC, 
		F.NM_FUNCIONARIO NOME_FUNC, 
        F.DT_ADMISSAO DATA_ADMISSAO,
        P.NM_PROJETO NOME_PROJETO,
		P.DT_INICIO  DATA_INICIO_PROJETO,
        E.DS_PAPEL_FUNC_PROJ PAPEL_FUNC_PROJETO,
        E.DT_ENTRADA DATA_ENTRADA_FUNC_PROJETO,
        E.DT_SAIDA DATA_SAIDA_FUNC_PROJETO
FROM 	T_SIP_FUNCIONARIO F INNER JOIN T_SIP_EXECUCAO_PROJ E
ON 		(F.CD_FUNC = E.CD_FUNC) INNER JOIN T_SIP_PROJETO P
ON      (E.CD_PROJETO = P.CD_PROJETO)
ORDER BY F.NM_FUNCIONARIO;

-- Slide 30
SELECT 	F.CD_FUNC, 
		F.NM_FUNCIONARIO, 
		F.DS_ESTADO_CIVIL,
		F.DT_NASCIMENTO,
		D.ID_DEPENDENTE NUMERO_DEPENDENTE,
		D.NM_DEPENDENTE,
		D.DT_NASCIMENTO
FROM 	T_SIP_FUNCIONARIO F LEFT JOIN T_SIP_DEPENDENTE D
ON 		(F.CD_FUNC = D.CD_FUNC);

-- Slide 31
SELECT 	F.CD_FUNC, 
		F.NM_FUNCIONARIO, 
		F.DS_ESTADO_CIVIL,
		F.DT_NASCIMENTO,
		D.ID_DEPENDENTE NUMERO_DEPENDENTE,
		D.NM_DEPENDENTE,
		D.DT_NASCIMENTO
FROM 	T_SIP_FUNCIONARIO F LEFT JOIN T_SIP_DEPENDENTE D
ON 		(F.CD_FUNC = D.CD_FUNC)
WHERE	D.CD_FUNC IS NULL
ORDER BY F.NM_FUNCIONARIO;

-- Slide 34
SELECT 	P.CD_PROJETO CODIGO_PROJETO,
		P.NM_PROJETO NOME_PROJETO,
		P.VL_BUDGET_PROJETO,
		P.DT_INICIO  DATA_INICIO_PROJETO,
		P.DT_TERMINO DATA_FIM_PROJETO,
		E.CD_FUNC	 COD_FUNC_ENTRADA_PROJETO,
		E.DS_PAPEL_FUNC_PROJ PAPEL_FUNC_PROJETO,
        E.DT_ENTRADA DATA_ENTRADA_FUNC_PROJETO,
        E.DT_SAIDA DATA_SAIDA_FUNC_PROJETO
FROM 	T_SIP_EXECUCAO_PROJ E RIGHT JOIN T_SIP_PROJETO P
ON      (E.CD_PROJETO = P.CD_PROJETO)
ORDER BY P.DT_INICIO;

-- Slide 35
SELECT 	P.CD_PROJETO CODIGO_PROJETO,
		P.NM_PROJETO NOME_PROJETO,
		P.VL_BUDGET_PROJETO,
		P.DT_INICIO  DATA_INICIO_PROJETO,
		P.DT_TERMINO DATA_FIM_PROJETO,
		E.CD_FUNC	 COD_FUNC_ENTRADA_PROJETO,
		E.DS_PAPEL_FUNC_PROJ PAPEL_FUNC_PROJETO,
        E.DT_ENTRADA DATA_ENTRADA_FUNC_PROJETO,
        E.DT_SAIDA DATA_SAIDA_FUNC_PROJETO
FROM 	T_SIP_EXECUCAO_PROJ E RIGHT JOIN T_SIP_PROJETO P
ON      (E.CD_PROJETO = P.CD_PROJETO)
WHERE   E.CD_PROJETO IS NULL
ORDER BY P.DT_INICIO;

-- Slide 38
SELECT 	F.CD_FUNC CODIGO_FUNC, 
		F.NM_FUNCIONARIO NOME_FUNC, 
        F.DT_ADMISSAO DATA_ADMISSAO,
        P.NM_PROJETO NOME_PROJETO,
		P.DT_INICIO  DATA_INICIO_PROJETO,
        E.DS_PAPEL_FUNC_PROJ PAPEL_FUNC_PROJETO,
        E.DT_ENTRADA DATA_ENTRADA_FUNC_PROJETO,
        E.DT_SAIDA DATA_SAIDA_FUNC_PROJETO
FROM 	T_SIP_FUNCIONARIO F FULL OUTER JOIN T_SIP_EXECUCAO_PROJ E
ON 		(F.CD_FUNC = E.CD_FUNC) FULL OUTER JOIN T_SIP_PROJETO P
ON      (E.CD_PROJETO = P.CD_PROJETO)
ORDER BY F.CD_FUNC, P.CD_PROJETO;

-- Slide 39
SELECT 	F.CD_FUNC CODIGO_FUNC, 
		F.NM_FUNCIONARIO NOME_FUNC, 
        F.DT_ADMISSAO DATA_ADMISSAO,
        P.NM_PROJETO NOME_PROJETO,
		P.DT_INICIO  DATA_INICIO_PROJETO,
        E.DS_PAPEL_FUNC_PROJ PAPEL_FUNC_PROJETO,
        E.DT_ENTRADA DATA_ENTRADA_FUNC_PROJETO,
        E.DT_SAIDA DATA_SAIDA_FUNC_PROJETO
FROM 	T_SIP_FUNCIONARIO F FULL OUTER JOIN T_SIP_EXECUCAO_PROJ E
ON 		(F.CD_FUNC = E.CD_FUNC) FULL OUTER JOIN T_SIP_PROJETO P
ON      (E.CD_PROJETO = P.CD_PROJETO)
WHERE  	F.CD_FUNC IS NULL OR E.CD_PROJETO IS NULL
ORDER BY F.CD_FUNC, P.CD_PROJETO;

-- Slide 43
SELECT 	P.CD_PESSOA CODIGO_FUNCIONARIO, 
        P.NM_PESSOA NOME_FUNCIONARIO, 
        P.DS_PAPEL PAPEL_DO_FUNCIONARIO, 
        P.DT_INICIO DATA_INICIO_FUNCIONARIO,
        G.CD_PESSOA CODIGO_GESTOR, 
        G.NM_PESSOA NOME_GESTOR, 
        G.DS_PAPEL PAPEL_DO_GESTOR, 
        G.DT_INICIO DATA_INICIO_GESTOR
FROM	T_PESSOA P LEFT JOIN T_PESSOA G
ON (P.CD_PESSOA_GESTOR = G.CD_PESSOA)
ORDER BY P.CD_PESSOA;

-- Slide 46
SELECT 	D.CD_DEPTO,
		D.NM_DEPTO,
		F.CD_FUNC, 
		F.NM_FUNCIONARIO, 
		F.DT_ADMISSAO, 
		F.VL_SALARIO
FROM 	T_SIP_DEPTO D CROSS JOIN T_SIP_FUNCIONARIO F
ORDER BY D.CD_DEPTO;
